### ISSUE TITLE
Self identify the version of the `publiccode.yml`

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#1]
The file should state what version of the `publiccode.yml` is. I feel that `version` is confusing since it might also be about the version of the package.

```yaml
_publiccode-yaml-version: 1.0.5
```

We can make this federated – or more self documenting – by adding a release tag:

```yaml
_publiccode-yaml-version: https://github.com/publiccodenet/publiccode.yml/releases/tag/1.0.5
```

**Comment by ruphy** [comment]
fixed on our @italia fork
