### ISSUE TITLE
Some 2 cents for thougths

### ISSUE THREAD

**Issue by pombredanne** [publiccodenet/publiccode.yml#12]
https://github.com/codemeta/codemeta may be of some interest?

I suggest trying to use terms that may be already defined in SPDX if possible. And for license you should consider expressions and not just an id. Licenses get sometimes complicated out there

For package references, you could also consider https://github.com/package-url/purl-spec/

**Comment by ruphy** [comment]
Hi,
yes, SPDX is meant as an expression. And it is definitely a good idea.

To give you an example, internally, we're using this as guideline: https://github.com/teamdigitale/licenses

**Comment by pombredanne** [comment]
You may want to check also https://reuse.software/

**Comment by ruphy** [comment]
implemented, thanks
