### ISSUE TITLE
Codebase status

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#13]
To be used so that it can be discovered:

* indicate a project status in the `README`
  * "Ideation" - Brainstorming phase
  * "Alpha" - Brainstorming phase
  * "Beta" - Brainstorming phase
  * "Production" - Finished Product, development ongoing
  * "Archival" - Finished Product, development no longer ongoing

**Comment by ruphy** [comment]
fixed under @italia
