### ISSUE TITLE
Evaluate schema.org structure

### ISSUE THREAD

**Issue by sbronzolo** [publiccodenet/publiccode.yml#15]
http://schema.org/SoftwareApplication
http://schema.org/WebSite

**Comment by bvhme** [comment]
Also, I'm pretty interested in the [Core Vocabularies for Public Services and Public Administrations published by ISA2](https://ec.europa.eu/isa2/solutions/core-vocabularies_en).

In regard to this perhaps it makes sense to make a more detailed overview of the relation of structure in this project also in relation to civic.json, g0v.json etc as mentioned in #7.

**Comment by bvhme** [comment]
If we use `camelCase` in stead of `kebab-case` #18 , we could try to stay as close to the schema.org keys as possible.

**Comment by sandervd** [comment]
Hi @bvhme 

I work as a developer on the Joinup platform (ISA2), and was made aware of your initiative by George Lobo.
Joinup (https://joinup.ec.europa.eu/) is a platform that hosts 'interoperability solutions' (more info on the site) and uses an RDF based data model to describe those solutions. Solutions could be things like Open Source software, standards, reference models, etc. The model also describes everything related to it: releases, distributions, licenses, contact information...
All of this is defined in the 'Asset Description Metadata Standard' (ADMS), which is derived, and compatible with the DCAT metadata standard used by Open Data portals.

The approach of having the metadata in you repository makes a lot of sense to me... Certainly an interesting project!
It would be really interesting if somehow we could 'transform' the metadata in the publiccode file in to full ADMS... :thinking: 

Anyway, here are some references
https://joinup.ec.europa.eu/release/adms-ap-joinup-version/20
https://github.com/SEMICeu/ADMS-AP

Let me know if you need more context on all of this, I can't guarantee that I'll have an answer on everything related, but I might be able to point you in the direction of some other people.

**Comment by bvhme** [comment]
Hey Sander,

I've been looking through some of the DOCX files scattered throughout the
joinup, and to be hones am having a bit of a hard time actually distilling
from this what lessons were learned in this process and what serves what
goal, as well as the standard entities we could use.

I understand that your standards contain some standard ways of describing
public administrations, however, I feel we could use some extra guidance on
this. I feel we're all also in a specific context and thus need a bit of a
broader view, as 'municipality' is for instance not really a clear
descriptor that says anything about the actual organisation.

We're trying to provide for an easy to use way to organise software around
its use and to signify it's context,

Do you think you could be of help with this?



Boris van Hoytema

—

   - E-mail boris@vanhoytema.com
   - Website bvh.me
   - Twitter twitter.com/bvhme
   - Facebook facebook.com/vanhoytema <http://www.facebook.com/vanhoytema>
   - LinkedIn linkedin.com/in/borisvanhoytema
   <http://nl.linkedin.com/in/borisvanhoytema>
