### ISSUE TITLE
Altre info da richiedere

### ISSUE THREAD

**Issue by sbronzolo** [publiccodenet/publiccode.yml#16]
* Sarebbe utile produrre una lista chiusa (vocabolario controllato) di 50 o 100 tag da utilizzare per descrivere il software italiano (max 5 tag dalla lista). Molto utile per creare relazioni tra progetti.
* Sarebbe utile introdurre una lista di fornitori della PA usando codice mepa e costruire su questa una sottosezione dedicata ai fornitori accreditati a progetti di riuso
* Sarebbe utile, così come si chiede se il sistema integra spid e pago pa, chiedere se usa Designers Italia UI kit e/o Designers Italia web toolkit
*Più in generale, sarebbe utile richiedere se interagisce con ciascuno dei progetti che sono "infrastrutture immateriali"

**Comment by bvhme** [comment]
Cool, I don't know what a MEPA code is and such, but these seem to be some valid points. Could you split them up in to multiple issues, then we can track them individually.

Thanks!
