### ISSUE TITLE
Key case convention and namespace convention

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#18]
The current notation of `kebab-case` keys is a difficult one as it parses difficultly to other languages such as JavaScript.

Perhaps we should consider using `camelCase`, so it would be `repoOwner` and `shortDescription`.

In addition to this, namespacing could perhaps be done with an underscore, eg `nld_rsinNummer`.

**Comment by ruphy** [comment]
I was not aware of parsing problems for `-`, in this case, :+1: for camelCase

**Comment by rasky** [comment]
No problem with camelcase.

**Comment by ruphy** [comment]
fixed
