### ISSUE TITLE
Multilingual and multinational support without being confusing

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#20]
We're dealing with both multiple languages and multiple countries here, as some countries are multilingual or some languages span multiple countries.

I'm affraid that if we use codes like [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) for languages and [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) for countries we're going to get confusions and collisions, although the level of overlap is not that big.

**Comment by rasky** [comment]
Suggestions?

**Comment by ruphy** [comment]
localization and countries are semantically very different concepts. They need separate keys, this is fixed in the latest @italia version
