### ISSUE TITLE
Register publiccode on w3id

### ISSUE THREAD

**Issue by ruphy** [publiccodenet/publiccode.yml#24]
We reference http://w3id.org/publiccode to specify the version name. We need to register it and point it to something.

**Comment by bvhme** [comment]
Yes, could we register it as `publiccode.yml` to be more specific?

**Comment by ruphy** [comment]
I wouldn't tie the permanent id to a specific format, but more to the concept!

**Comment by ruphy** [comment]
Opened a PR: https://github.com/perma-id/w3id.org/pull/997

**Comment by bvhme** [comment]
Cool, should we then not perhaps put a `/yml/` in between there, for if we
need to manage versions that are in a different format or context in the
future?

**Comment by ruphy** [comment]
Sure thing! I just added a very basic redirect for now, pointing to our github pages. Comments on how to structure the permaID are very welcome 😄

**Comment by ruphy** [comment]
We got the ID, closing this issue!
