### ISSUE TITLE
In the example publiccode.yml there are invalid values.

### ISSUE THREAD

**Issue by r3vit** [publiccodenet/publiccode.yml#29]
The example file `publiccode.yml` should be a valid example.
There are some issues:

- Tags should be referred to [acceptable values list](https://github.com/publiccodenet/publiccode.yml/blob/develop/schema.md#key-tags). (Free tags are for not-in-list tags, right?)
- intendedAudience/onlyFor value should be one (or more) of [these](https://github.com/publiccodenet/publiccode.yml/blob/develop/pa-types.md).
- Dates: not a real issue, but for consistency should be with quotes or without quotes. (`2017-04-15` or `"2017-04-15 "`)

[Here](https://github.com/r3vit/publiccode.yml-parser-go/blob/master/tests/valid.yml) there is a valid example :) (note that the dates are valid but inconsistent)

**Comment by ruphy** [comment]
thanks a lot for all these notes!
