### ISSUE TITLE
Missing description for "interoperabile" key in italian extension.

### ISSUE THREAD

**Issue by r3vit** [publiccodenet/publiccode.yml#30]
There is no description for key `ita/interoperabile` in [schema.it.md](https://github.com/publiccodenet/publiccode.yml/blob/develop/schema.it.md) (but it's used in [example/publiccode.yml](https://github.com/publiccodenet/publiccode.yml/blob/develop/example/publiccode.yml) )

**Comment by ruphy** [comment]
We need to add it back quoting Art. 73 of CAD

**Comment by ruphy** [comment]
Fixed
