### ISSUE TITLE
Country-specific country-name key in example publiccode.yml doesn't satisfy the schema definition.

### ISSUE THREAD

**Issue by r3vit** [publiccodenet/publiccode.yml#31]
In [schema.md](https://github.com/publiccodenet/publiccode.yml/blob/develop/schema.md) description the [Country-specific key](https://github.com/publiccodenet/publiccode.yml/blob/develop/schema.md#country-specific-extensions) is defined as:
>All country-specific sections are contained in a section named with the two-letter lowercase ISO 3166-1 alpha-2 country code. 

In the [example/publiccode.yml](https://github.com/publiccodenet/publiccode.yml/blob/develop/example/publiccode.yml) the extension country is named using [ISO_3166-1_alpha-3](https://it.wikipedia.org/wiki/ISO_3166-1_alpha-3) instead of [ISO_3166-1_alpha-2](https://it.wikipedia.org/wiki/ISO_3166-1_alpha-2).

**Comment by lussoluca** [comment]
@ruphy could you please check this?

**Comment by ruphy** [comment]
Thanks. This was a mistake in the example file. I changed it.
