### ISSUE TITLE
`civic.json` and `g0v.json` are similar projects

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#7]
Would [`civic.json`](https://github.com/BetaNYC/civic.json/blob/master/specification.md) from [OpenDC](http://open.dc.gov/civic.json/) or [`g0v.json`](https://github.com/g0v/g0v.json) solve our use cases?

(Suggested by @KrzysztofMadejski on the Code4All Slack)

**Comment by bvhme** [comment]
Here is a discussion from `civic.json`s issues about adopting fields for government: https://github.com/BetaNYC/civic.json/issues/21

**Comment by ruphy** [comment]
I integrated all these fields in the current version of publiccode 💪
