### ISSUE TITLE
Consider JSON over YML because it is easier to consume over REST

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#8]
Suggested by @milovanderlinden on the Code4All Slack.

**Comment by bvhme** [comment]
As a counter argument, I feel that JSON is a lot less ergonomic for developers to add to new projects. Let alone civil servants to read.

**Comment by ruphy** [comment]
tbh I believe YAML is way more expressive, and it is a JSON subset anyways

**Comment by bvhme** [comment]
Well, technically the YAML specification has some more complex types
available and can actually do more powerful lifting than JSON in some
situations.

Why I love YAML in the way that we are using it, as a subset of JSON, is
because I believe it is easy to read also for non-technical people, who are
I think an important part of our audience :)


Boris van Hoytema

—

   - E-mail boris@vanhoytema.com
   - Website bvh.me
   - Twitter twitter.com/bvhme
   - Facebook facebook.com/vanhoytema <http://www.facebook.com/vanhoytema>
   - LinkedIn linkedin.com/in/borisvanhoytema
   <http://nl.linkedin.com/in/borisvanhoytema>

**Comment by ruphy** [comment]
after a few days of thought, I agree with what you say. I believe that once everything is properly documented, we can always leave some freedom and/or offer a conversion service. For example we will parse all publiccode we find on Developers Italia, and we can offer a public interface to scrape them from our site... at this point json become easy to drop in.

**Comment by bvhme** [comment]
I would definetely opt for YAML for that reason, and then others can do the
conversion. I think our focus should be on an understandable data format
for technical and non-technical people alike in the repo.

**Comment by milovanderlinden** [comment]
I have written a small microservice that does yaml <-> json. It is available at https://github.com/codefornl/node-jsonyml so feel free to have yml as main choice and let those that prefer json convert it (possibly even on the fly)

**Comment by ruphy** [comment]
This looks amazing! Thanks for sharing it!
I am closing this issue since it seems like consensus for YAML has been reached.
